services:
  server:
    container_name: vpn      
    privileged: true
    build: .
    ports:
      - 443:443/tcp
      - 443:443/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/etc/ocserv/

    