
name: Build
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: deploy

permissions:
  packages: write

env:
  ARM_CLIENT_SECRET: ${{ secrets.AAD_TERRAFORM_SECRET }}
  ARM_CLIENT_ID: ${{ vars.AAD_TERRAFORM_CLIENT_ID }}
  ARM_TENANT_ID:  ${{ vars.AAD_TENANT_ID }}

jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ github.actor }}/cisco-vpn-gateway:latest
          push: true